### ISSUE TITLE
Client Synchronization

### ISSUE THREAD

**Issue by joshbenz** [PPA-Enterprises/crispy-fiesta#5]
### Current State

There is no client-server synchronization when changes are made concurrently/asynchronously to database records.

---

### Limitations

The current state will lead to undefined behavior in asynchronous and concurrent use cases of the web application

---

### Proposed Changes

- Option 1: Client side polling
- Option 2: websockets mechanism
- Option 3: websocket/client polling hybrid mechanism
- Option 4: Server Sent Events

---

### Justification

This is an important aspect of asynchronous and concurrent use cases

**Comment by thlinux** [comment]
Which option is the more standard way? @joshbenz

**Comment by joshbenz** [comment]
> Which option is the more standard way? @joshbenz 

They're all standard as far as I know, except maybe option 3. Option 1 also has another variant called a Long Poll. Server Sent Events is the newest but is probably the most applicable for what we are trying to do.

**Comment by thlinux** [comment]
Option 4 it is then!
